from pathlib import Path


calibration_position = {
    # Val
    "scene_041": sorted([str(p) for p in Path("/workspace/videos/val/scene_041").glob("**/calibration.json")]),
    "scene_042": sorted([str(p) for p in Path("/workspace/videos/val/scene_042").glob("**/calibration.json")]),
    "scene_043": sorted([str(p) for p in Path("/workspace/videos/val/scene_043").glob("**/calibration.json")]),
    "scene_044": sorted([str(p) for p in Path("/workspace/videos/val/scene_044").glob("**/calibration.json")]),
    "scene_045": sorted([str(p) for p in Path("/workspace/videos/val/scene_045").glob("**/calibration.json")]),
    "scene_046": sorted([str(p) for p in Path("/workspace/videos/val/scene_046").glob("**/calibration.json")]),
    "scene_047": sorted([str(p) for p in Path("/workspace/videos/val/scene_047").glob("**/calibration.json")]),
    "scene_048": sorted([str(p) for p in Path("/workspace/videos/val/scene_048").glob("**/calibration.json")]),
    "scene_049": sorted([str(p) for p in Path("/workspace/videos/val/scene_049").glob("**/calibration.json")]),
    "scene_050": sorted([str(p) for p in Path("/workspace/videos/val/scene_050").glob("**/calibration.json")]),
    "scene_051": sorted([str(p) for p in Path("/workspace/videos/val/scene_051").glob("**/calibration.json")]),
    "scene_052": sorted([str(p) for p in Path("/workspace/videos/val/scene_052").glob("**/calibration.json")]),
    "scene_053": sorted([str(p) for p in Path("/workspace/videos/val/scene_053").glob("**/calibration.json")]),
    "scene_054": sorted([str(p) for p in Path("/workspace/videos/val/scene_054").glob("**/calibration.json")]),
    "scene_055": sorted([str(p) for p in Path("/workspace/videos/val/scene_055").glob("**/calibration.json")]),
    "scene_056": sorted([str(p) for p in Path("/workspace/videos/val/scene_056").glob("**/calibration.json")]),
    "scene_057": sorted([str(p) for p in Path("/workspace/videos/val/scene_057").glob("**/calibration.json")]),
    "scene_058": sorted([str(p) for p in Path("/workspace/videos/val/scene_058").glob("**/calibration.json")]),
    "scene_059": sorted([str(p) for p in Path("/workspace/videos/val/scene_059").glob("**/calibration.json")]),
    "scene_060": sorted([str(p) for p in Path("/workspace/videos/val/scene_060").glob("**/calibration.json")]),

    # Test
    "scene_061": sorted([str(p) for p in Path("/workspace/videos/test/scene_061").glob("**/calibration.json")]),
    "scene_062": sorted([str(p) for p in Path("/workspace/videos/test/scene_062").glob("**/calibration.json")]),
    "scene_063": sorted([str(p) for p in Path("/workspace/videos/test/scene_063").glob("**/calibration.json")]),
    "scene_064": sorted([str(p) for p in Path("/workspace/videos/test/scene_064").glob("**/calibration.json")]),
    "scene_065": sorted([str(p) for p in Path("/workspace/videos/test/scene_065").glob("**/calibration.json")]),
    "scene_066": sorted([str(p) for p in Path("/workspace/videos/test/scene_066").glob("**/calibration.json")]),
    "scene_067": sorted([str(p) for p in Path("/workspace/videos/test/scene_067").glob("**/calibration.json")]),
    "scene_068": sorted([str(p) for p in Path("/workspace/videos/test/scene_068").glob("**/calibration.json")]),
    "scene_069": sorted([str(p) for p in Path("/workspace/videos/test/scene_069").glob("**/calibration.json")]),
    "scene_070": sorted([str(p) for p in Path("/workspace/videos/test/scene_070").glob("**/calibration.json")]),
    "scene_071": sorted([str(p) for p in Path("/workspace/videos/test/scene_071").glob("**/calibration.json")]),
    "scene_072": sorted([str(p) for p in Path("/workspace/videos/test/scene_072").glob("**/calibration.json")]),
    "scene_073": sorted([str(p) for p in Path("/workspace/videos/test/scene_073").glob("**/calibration.json")]),
    "scene_074": sorted([str(p) for p in Path("/workspace/videos/test/scene_074").glob("**/calibration.json")]),
    "scene_075": sorted([str(p) for p in Path("/workspace/videos/test/scene_075").glob("**/calibration.json")]),
    "scene_076": sorted([str(p) for p in Path("/workspace/videos/test/scene_076").glob("**/calibration.json")]),
    "scene_077": sorted([str(p) for p in Path("/workspace/videos/test/scene_077").glob("**/calibration.json")]),
    "scene_078": sorted([str(p) for p in Path("/workspace/videos/test/scene_078").glob("**/calibration.json")]),
    "scene_079": sorted([str(p) for p in Path("/workspace/videos/test/scene_079").glob("**/calibration.json")]),
    "scene_080": sorted([str(p) for p in Path("/workspace/videos/test/scene_080").glob("**/calibration.json")]),
    "scene_081": sorted([str(p) for p in Path("/workspace/videos/test/scene_081").glob("**/calibration.json")]),
    "scene_082": sorted([str(p) for p in Path("/workspace/videos/test/scene_082").glob("**/calibration.json")]),
    "scene_083": sorted([str(p) for p in Path("/workspace/videos/test/scene_083").glob("**/calibration.json")]),
    "scene_084": sorted([str(p) for p in Path("/workspace/videos/test/scene_084").glob("**/calibration.json")]),
    "scene_085": sorted([str(p) for p in Path("/workspace/videos/test/scene_085").glob("**/calibration.json")]),
    "scene_086": sorted([str(p) for p in Path("/workspace/videos/test/scene_086").glob("**/calibration.json")]),
    "scene_087": sorted([str(p) for p in Path("/workspace/videos/test/scene_087").glob("**/calibration.json")]),
    "scene_088": sorted([str(p) for p in Path("/workspace/videos/test/scene_088").glob("**/calibration.json")]),
    "scene_089": sorted([str(p) for p in Path("/workspace/videos/test/scene_089").glob("**/calibration.json")]),
    "scene_090": sorted([str(p) for p in Path("/workspace/videos/test/scene_090").glob("**/calibration.json")]),
}
